[project]
name = "toolbox"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "h5py>=3.15.1",
    "matplotlib>=3.10.8",
    "numpy>=2.2.6",
    "pillow>=12.1.0",
    "pyinstaller>=6.18.0",
    "pyside6<6.10",
    "requests>=2.32.5",
    “gdal==3.4.3"
]
