[project]
name = "toolbox"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dmgbuild>=1.6.7",
    "h5py>=3.15.1",
    "matplotlib>=3.10.8",
    "numpy>=1.21.0,<2.0",
    "opencv-python==4.10.0.84",
    "pillow>=12.1.0",
    "pyqtgraph>=0.13.7",
    "pyinstaller>=6.18.0",
    "pyside6<6.10",
    "requests>=2.32.5",
    "shapely>=2.0.6",
    "gdal==3.4.3",
]
